# Generated by Django 3.2.4 on 2021-11-20 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartGrouped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('quality', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.groupedproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CartVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('quality', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.variableproductattributes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='orderFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_final_price', models.FloatField(blank=True, null=True)),
                ('product_weight', models.FloatField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('quality', models.TextField(blank=True, null=True)),
                ('quantity', models.TextField(blank=True, null=True)),
                ('shiping_type', models.CharField(blank=True, max_length=300, null=True)),
                ('shiping_charges', models.FloatField(blank=True, null=True)),
                ('shiping_zone', models.CharField(blank=True, max_length=300, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('gst_applied', models.FloatField(blank=True, null=True)),
                ('packing_charges', models.FloatField(blank=True, null=True)),
                ('base_price', models.FloatField(blank=True, null=True)),
                ('product_margin', models.FloatField(blank=True, null=True)),
                ('customer_first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_phone_number', models.IntegerField(blank=True, null=True)),
                ('customer_zipcode', models.IntegerField(blank=True, null=True)),
                ('customer_country', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_town', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('coupon_Applied_type', models.TextField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=150, null=True)),
                ('coupon_discount', models.FloatField(blank=True, null=True)),
                ('coupon_applied', models.BooleanField(blank=True, default=False, null=True)),
                ('final_price_coupon_applied', models.IntegerField(blank=True, null=True)),
                ('order_Status', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='orderImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cartimage')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.orderfinal')),
            ],
        ),
        migrations.CreateModel(
            name='DifferentShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_phone_number', models.IntegerField(blank=True, null=True)),
                ('customer_zipcode', models.IntegerField(blank=True, null=True)),
                ('customer_country', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_town', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.orderfinal')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(blank=True, max_length=200, null=True)),
                ('registred_address', models.CharField(blank=True, max_length=200, null=True)),
                ('registered_name', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.orderfinal')),
            ],
        ),
        migrations.CreateModel(
            name='cartVariableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cartimage')),
                ('cartitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.cartvariable')),
            ],
        ),
        migrations.CreateModel(
            name='Cartsimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('quality', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.simpleproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='cartSimleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cartimage')),
                ('cartitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.cartsimple')),
            ],
        ),
        migrations.CreateModel(
            name='cartGroupedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='cartimage')),
                ('cartitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.cartgrouped')),
            ],
        ),
    ]
